Need to install numpy==1.26.4, bioservices, shap==0.42.0, gprofiler-official

In [1]:
import numpy as np
import shap
import pandas as pd

IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html

In [2]:
import mlmarker

In [3]:
model = mlmarker.MLMarker(binary=False)

Trying to unpickle estimator DecisionTreeClassifier from version 1.5.1 when using version 1.6.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
Trying to unpickle estimator RandomForestClassifier from version 1.5.1 when using version 1.6.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations

In [4]:
df = pd.read_csv('C:\\Users\\tinec\\git\\MLMarker-streamlit\\testsample.tsv', sep='\\t')
df

Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.

,sample,A0A075B6H7,A0A075B6H8,A0A075B6H9,A0A075B6I0,A0A075B6I9,A0A075B6J9,A0A075B6K2,A0A075B6K4,A0A075B6K5,...,Q9Y6V0,Q9Y6V7,Q9Y6W3,Q9Y6W5,Q9Y6X3,Q9Y6X5,Q9Y6X8,Q9Y6X9,Q9Y6Y0,Q9Y6Y8
0,Liver,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.000330,NaN,NaN,NaN,NaN,NaN,NaN
1,Brain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000144,NaN,0.000031,0.000076,NaN,0.000111,NaN,0.000012,0.00001,0.000025
2,Kidney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.001020,NaN,NaN,NaN,NaN,NaN,NaN
3,Colon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.000134,NaN,NaN,NaN,NaN,NaN,NaN
4,Liver,0.000307,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.000157,NaN,0.000035,NaN,0.000107
5,Blood plasma,0.006763,NaN,0.003296,NaN,NaN,0.003324,NaN,0.003411,0.010233,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Blood serum,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Colon cancer,0.001031,NaN,NaN,0.000327,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Stomach cancer,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
model.load_sample(df.iloc[1:2,:])
model.explainability.get_shap_values(n_preds=34)

,A0A075B6H7,A0A075B6H8,A0A075B6H9,A0A075B6I0,A0A075B6I9,A0A075B6J9,A0A075B6K2,A0A075B6K4,A0A075B6K5,A0A075B6Q5,...,Q9Y6V0,Q9Y6V7,Q9Y6W3,Q9Y6W5,Q9Y6X3,Q9Y6X5,Q9Y6X8,Q9Y6X9,Q9Y6Y0,Q9Y6Y8
tissue,,,,,,,,,,,,,,,,,,,,,
Brain,0.00000,0.0,0.0,0.00016,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.00001,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.0,0.00001
Tonsil,0.00000,0.0,-0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00000,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.0,0.00000
Liver,-0.00000,0.0,0.0,0.00001,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.00001,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.0,-0.00001
Heart,0.00000,0.0,0.0,0.00001,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.00000,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.0,0.00000
Lung,0.00000,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.00007,0.0,0.00000,-0.00000,0.0,0.0,0.0,0.0,0.0,-0.00001
Stomach,0.00000,0.0,0.0,-0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.00000,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.0,-0.00001
Endometrium,0.00000,0.0,0.0,0.00002,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.00001,0.0,0.00000,0.00002,0.0,0.0,0.0,0.0,0.0,0.00000
Smooth muscle,0.00000,0.0,0.0,-0.00001,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.00001,0.0,-0.00002,0.00000,0.0,0.0,0.0,0.0,0.0,0.00000
Spleen,0.00001,0.0,0.0,0.00001,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.00007,0.0,-0.00001,0.00000,0.0,0.0,0.0,0.0,0.0,-0.00001
Colon,0.00000,0.0,0.0,0.00001,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.00000,0.0,0.00001,0.00000,0.0,0.0,0.0,0.0,0.0,0.00002
Esophagus,0.00000,0.0,0.0,-0.00001,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.00001,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.0,0.00000
Ovary,-0.00000,0.0,0.0,-0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.00001,0.0,0.00001,-0.00000,0.0,0.0,0.0,0.0,0.0,0.00006
Appendix,0.00000,0.0,0.0,0.00001,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.00003,0.0,0.00000,0.00005,0.0,0.0,0.0,0.0,0.0,-0.00001
Parotid gland,0.00000,0.0,0.0,0.00002,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00000,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.0,-0.00000
Lymph node,0.00000,0.0,0.0,0.00001,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.00003,0.0,0.00000,0.00001,0.0,0.0,0.0,0.0,0.0,0.00000
Urinary bladder,0.00000,0.0,0.0,0.00003,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.00003,0.0,0.00000,-0.00001,0.0,0.0,0.0,0.0,0.0,-0.00008
Skeletal muscle,0.00000,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00000,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.0,0.00000
Placenta,-0.00000,0.0,0.0,-0.00012,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.00001,0.0,0.00000,0.00001,0.0,0.0,0.0,0.0,0.0,0.00000
Adipose tissue,0.00000,0.0,0.0,-0.00002,0.0,-0.0,0.0,0.0,0.0,0.0,...,-0.00003,0.0,0.00000,0.00001,0.0,0.0,0.0,0.0,0.0,0.00001
Rectum,-0.00001,0.0,0.0,0.00002,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.00001,0.0,-0.00001,0.00000,0.0,0.0,0.0,0.0,0.0,-0.00001
Pituitary gland,0.00000,0.0,0.0,0.00001,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00058,0.0,0.00000,-0.00000,0.0,0.0,0.0,0.0,0.0,0.00000
Testis,0.00000,0.0,0.0,0.00001,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.00011,0.0,0.00000,0.00001,0.0,0.0,0.0,0.0,0.0,0.00001
Duodenum,0.00000,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.00001,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.0,0.00000
Kidney,0.00000,0.0,0.0,0.00001,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.00004,0.0,0.00001,0.00000,0.0,0.0,0.0,0.0,0.0,0.00002
Adrenal gland,0.00000,0.0,0.0,0.00001,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.00001,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.0,0.00000
B-cells,0.00000,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.00002,0.0,0.00000,-0.00012,0.0,0.0,0.0,0.0,0.0,0.00001
Bone marrow,0.00000,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.00001,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.0,0.00000
Monocytes,0.00000,0.0,0.0,0.00001,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.00003,0.0,0.00000,0.00002,0.0,0.0,0.0,0.0,0.0,0.00000
Nasal Polyps,0.00000,0.0,0.0,-0.00022,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00000,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.0,0.00000
Oviduct,-0.00000,0.0,0.0,0.00001,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00000,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.0,0.00000
Prostate,-0.00000,0.0,0.0,0.00002,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00000,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.0,0.00000
Salivary gland,0.00000,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.00001,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.0,0.00000
Small intestine,0.00000,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.00000,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,-0.0,0.00000
Thyroid,0.00000,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.00001,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.0,-0.00000

In [12]:
shap.__version__

'0.41.0'

# HERE

In [19]:
df

,A0A024RBG1,A0A075B6H7,A0A075B6H8,A0A075B6H9,A0A075B6I0,A0A075B6I1,A0A075B6I7,A0A075B6I9,A0A075B6J1,A0A075B6J6,...,Q9Y6X8,Q9Y6X9,Q9Y6Y0,Q9Y6Y1,Q9Y6Y8,Q9Y6Y9,Q9Y6Z4,Q9Y6Z5,Q9Y6Z7,W5XKT8
sample,,,,,,,,,,,,,,,,,,,,,
Liver,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Brain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.000012,0.00001,NaN,0.000025,NaN,NaN,NaN,NaN,NaN
Kidney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Colon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Liver,NaN,0.000307,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.000035,NaN,NaN,0.000107,NaN,NaN,NaN,NaN,NaN
Blood plasma,NaN,0.006763,NaN,0.003296,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Blood serum,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Colon cancer,NaN,0.001031,NaN,NaN,0.000327,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Stomach cancer,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
mlm = ['sample'] +

In [24]:
df[model.get_model_features()].to_csv('testsample.tsv', sep = '\t')

In [3]:
# Replicate Home.py processing for debugging
from sklearn.preprocessing import MinMaxScaler

# Read file (same as Home.py read_file)
df = pd.read_csv('testsample.tsv', sep='\t')

# Clean input (same as Home.py clean_input)
df.columns = df.columns.str.strip()
df = df.set_index(df.columns[0])
df = df.apply(pd.to_numeric, errors='coerce')

print("After clean_input:")
print(df.shape)
print(df.head())

After clean_input:
(9, 11891)
        A0A024RBG1  A0A075B6H7  A0A075B6H8  A0A075B6H9  A0A075B6I0  \
sample
Liver          NaN         NaN         NaN         NaN         NaN
Brain          NaN         NaN         NaN         NaN         NaN
Kidney         NaN         NaN         NaN         NaN         NaN
Colon          NaN         NaN         NaN         NaN         NaN
Liver          NaN    0.000307         NaN         NaN         NaN

        A0A075B6I1  A0A075B6I7  A0A075B6I9  A0A075B6J1  A0A075B6J6  ...  \
sample                                                              ...
Liver          NaN         NaN         NaN         NaN         NaN  ...
Brain          NaN         NaN         NaN         NaN         NaN  ...
Kidney         NaN         NaN         NaN         NaN         NaN  ...
Colon          NaN         NaN         NaN         NaN         NaN  ...
Liver          NaN         NaN         NaN         NaN         NaN  ...

        Q9Y6X8    Q9Y6X9   Q9Y6Y0  Q9Y6Y1    Q9Y6Y8  Q9Y6Y9  Q9Y6Z4  Q9Y6Z5  \
sample
Liver      NaN       NaN      NaN     NaN       NaN     NaN     NaN     NaN
Brain      NaN  0.000012  0.00001     NaN  0.000025     NaN     NaN     NaN
Kidney     NaN       NaN      NaN     NaN       NaN     NaN     NaN     NaN
Colon      NaN       NaN      NaN     NaN       NaN     NaN     NaN     NaN
Liver      NaN  0.000035      NaN     NaN  0.000107     NaN     NaN     NaN

        Q9Y6Z7  W5XKT8
sample
Liver      NaN     NaN
Brain      NaN     NaN
Kidney     NaN     NaN
Colon      NaN     NaN
Liver      NaN     NaN

[5 rows x 11891 columns]

In [4]:
# Select one sample (same as Home.py)
sample_df = df.iloc[[0]]
print("Sample selected:")
print(sample_df.shape)
print(sample_df.index)

Sample selected:
(1, 11891)
Index(['Liver'], dtype='object', name='sample')

In [5]:
# Preprocess sample (same as Home.py preprocess_sample with "Quantified proteins")
def preprocess_sample(sample_df, method):
    # Fill NaN values with 0 before processing for MLMarker
    sample_df = sample_df.fillna(0)
    if method == "Quantified proteins":
        scaler = MinMaxScaler()
        return pd.DataFrame(scaler.fit_transform(sample_df.T).T,
                            index=sample_df.index, columns=sample_df.columns)
    else:
        return sample_df.map(lambda x: 1 if x > 0 else 0)

processed_sample = preprocess_sample(sample_df, "Quantified proteins")
print("Processed sample shape:", processed_sample.shape)
print("Min/Max values:", processed_sample.values.min(), processed_sample.values.max())

Processed sample shape: (1, 11891)
Min/Max values: 0.0 1.0

In [6]:
# Load model and run prediction (same as Home.py)
model = mlmarker.MLMarker(penalty_factor=0, binary=False)
model.load_sample(processed_sample)

print("Model loaded successfully")
print("Sample in model shape:", model.explainability.sample.shape)

Trying to unpickle estimator DecisionTreeClassifier from version 1.5.1 when using version 1.6.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
Trying to unpickle estimator RandomForestClassifier from version 1.5.1 when using version 1.6.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations

Model loaded successfully
Sample in model shape: (1, 5979)

In [10]:
# This is the call that fails in Home.py - try it here
try:
    prediction_df = model.explainability.get_shap_values(n_preds=50)
    print("Success! prediction_df shape:", prediction_df.shape)
    print(prediction_df.head())
except Exception as e:
    print(f"Error: {type(e).__name__}: {e}")

Success! prediction_df shape: (34, 5979)
            A0A075B6H7  A0A075B6H8  A0A075B6H9  A0A075B6I0  A0A075B6I9  \
tissue
Liver             -0.0         0.0         0.0     0.00010         0.0
Lung               0.0         0.0         0.0     0.00000         0.0
Kidney             0.0         0.0         0.0     0.00005         0.0
Lymph node         0.0         0.0         0.0     0.00001         0.0
Colon              0.0         0.0         0.0    -0.00001         0.0

            A0A075B6J9  A0A075B6K2  A0A075B6K4  A0A075B6K5  A0A075B6Q5  ...  \
tissue                                                                  ...
Liver          0.00000         0.0         0.0         0.0         0.0  ...
Lung           0.00000         0.0         0.0         0.0         0.0  ...
Kidney         0.00002         0.0         0.0         0.0         0.0  ...
Lymph node     0.00000         0.0         0.0         0.0         0.0  ...
Colon          0.00000         0.0         0.0         0.0         0.0  ...

             Q9Y6V0  Q9Y6V7  Q9Y6W3   Q9Y6W5  Q9Y6X3  Q9Y6X5  Q9Y6X8  Q9Y6X9  \
tissue
Liver       0.00000     0.0     0.0  0.00000     0.0     0.0     0.0     0.0
Lung        0.00001     0.0     0.0 -0.00000     0.0     0.0     0.0     0.0
Kidney      0.00001     0.0     0.0 -0.00000     0.0     0.0     0.0     0.0
Lymph node  0.00001     0.0     0.0  0.00001     0.0     0.0     0.0     0.0
Colon       0.00000     0.0     0.0  0.00000     0.0     0.0     0.0     0.0

            Q9Y6Y0   Q9Y6Y8
tissue
Liver          0.0 -0.00000
Lung           0.0 -0.00004
Kidney         0.0  0.00002
Lymph node     0.0  0.00000
Colon          0.0  0.00002

[5 rows x 5979 columns]

In [11]:
mlmarker.__version__

'0.1.6'

In [8]:
# Compare: Raw sample (works in cell 19) vs Processed sample
print("=== Comparison ===")
print("Raw df.iloc[0:1,:] shape:", df.iloc[0:1,:].shape)
print("Processed sample shape:", processed_sample.shape)
print("\nRaw sample has index as first column included?", 'sample' in df.columns)
print("Processed sample columns (first 5):", processed_sample.columns[:5].tolist())

=== Comparison ===
Raw df.iloc[0:1,:] shape: (1, 11891)
Processed sample shape: (1, 11891)

Raw sample has index as first column included? False
Processed sample columns (first 5): ['A0A024RBG1', 'A0A075B6H7', 'A0A075B6H8', 'A0A075B6H9', 'A0A075B6I0']

In [9]:
# Print exact versions that work - use these in requirements.txt
import sklearn
print("Working environment versions:")
print(f"numpy=={np.__version__}")
print(f"shap=={shap.__version__}")
print(f"scikit-learn=={sklearn.__version__}")
print(f"mlmarker=={mlmarker.__version__}")
print(f"pandas=={pd.__version__}")

Working environment versions:
numpy==1.23.5
shap==0.42.0
scikit-learn==1.6.1
mlmarker==0.1.6
pandas==2.2.3

['A0A075B6H7',
 'A0A075B6H8',
 'A0A075B6H9',
 'A0A075B6I0',
 'A0A075B6I9',
 'A0A075B6J9',
 'A0A075B6K2',
 'A0A075B6K4',
 'A0A075B6K5',
 'A0A075B6Q5',
 'A0A075B6R2',
 'A0A075B6S5',
 'A0A087WSY4',
 'A0A087WSY6',
 'A0A0A0MS14',
 'A0A0A0MS15',
 'A0A0B4J1U3',
 'A0A0B4J1U7',
 'A0A0B4J1V0',
 'A0A0B4J1V1',
 'A0A0B4J1V2',
 'A0A0B4J1V6',
 'A0A0B4J1X8',
 'A0A0B4J1Y8',
 'A0A0B4J1Z2',
 'A0A0B4J2F0',
 'A0A0C4DH25',
 'A0A0C4DH29',
 'A0A0C4DH30',
 'A0A0C4DH31',
 'A0A0C4DH32',
 'A0A0C4DH33',
 'A0A0C4DH34',
 'A0A0C4DH35',
 'A0A0C4DH36',
 'A0A0C4DH38',
 'A0A0C4DH39',
 'A0A0C4DH42',
 'A0A0C4DH43',
 'A0A0G2JMI3',
 'A0A0J9YX35',
 'A0A0J9YXX1',
 'A0A1B0GUS4',
 'A0AVT1',
 'A0JNW5',
 'A0MZ66',
 'A0PJW6',
 'A0PK00',
 'A1A4S6',
 'A1IGU5',
 'A1L020',
 'A1L4H1',
 'A1X283',
 'A2A2Y4',
 'A2A3N6',
 'A2RRP1',
 'A2RUC4',
 'A2VEC9',
 'A3KMH1',
 'A3KN83',
 'A4D126',
 'A4D1E9',
 'A4D1S5',
 'A4D2B0',
 'A4FU01',
 'A5A3E0',
 'A5PLN9',
 'A5YKK6',
 'A5YM72',
 'A6NC98',
 'A6NCN2',
 'A6NCS6',
 'A6ND36',
 'A6ND91',
 'A6NDG6',
 'A6NDU8',
 'A6NEL2',
 'A6NFI3',
 'A6NHL2',
 'A6NHQ2',
 'A6NHR9',
 'A6NHT5',
 'A6NHX0',
 'A6NHZ5',
 'A6NI79',
 'A6NIH7',
 'A6NJ78',
 'A6NJG2',
 'A6NKD9',
 'A6NKG5',
 'A6NKN8',
 'A6NLP5',
 'A6NMY6',
 'A6NMZ7',
 'A6NNZ2',
 'A7KAX9',
 'A8K2U0',
 'A8K7I4',
 'A8K855',
 'A8MTJ3',
 'A8MTT3',
 'A8MVS5',
 'A8MVW0',
 'A8MWX3',
 'A8MXV4',
 'A8MYA2',
 'B0I1T2',
 'B5MCN3',
 'B7ZBB8',
 'C9J069',
 'C9J7I0',
 'C9JRZ8',
 'E0CX11',
 'E5RJM6',
 'E9PAV3',
 'E9PRG8',
 'H3BV60',
 'H7BZ55',
 'L0R6Q1',
 'L0R819',
 'L0R8F8',
 'O00115',
 'O00139',
 'O00148',
 'O00151',
 'O00154',
 'O00159',
 'O00160',
 'O00165',
 'O00170',
 'O00178',
 'O00182',
 'O00186',
 'O00187',
 'O00193',
 'O00194',
 'O00203',
 'O00204',
 'O00231',
 'O00232',
 'O00244',
 'O00264',
 'O00267',
 'O00268',
 'O00273',
 'O00287',
 'O00291',
 'O00299',
 'O00303',
 'O00308',
 'O00330',
 'O00339',
 'O00391',
 'O00399',
 'O00401',
 'O00411',
 'O00418',
 'O00425',
 'O00429',
 'O00442',
 'O00443',
 'O00459',
 'O00463',
 'O00468',
 'O00478',
 'O00479',
 'O00483',
 'O00487',
 'O00499',
 'O00505',
 'O00506',
 'O00507',
 'O00512',
 'O00519',
 'O00534',
 'O00562',
 'O00566',
 'O00567',
 'O00592',
 'O00602',
 'O00622',
 'O00625',
 'O00629',
 'O00635',
 'O00743',
 'O00748',
 'O00754',
 'O00757',
 'O00763',
 'O00767',
 'O14494',
 'O14495',
 'O14497',
 'O14498',
 'O14523',
 'O14530',
 'O14531',
 'O14544',
 'O14545',
 'O14548',
 'O14556',
 'O14594',
 'O14604',
 'O14613',
 'O14617',
 'O14646',
 'O14647',
 'O14654',
 'O14656',
 'O14657',
 'O14672',
 'O14684',
 'O14686',
 'O14732',
 'O14733',
 'O14745',
 'O14756',
 'O14772',
 'O14775',
 'O14776',
 'O14791',
 'O14802',
 'O14807',
 'O14818',
 'O14828',
 'O14841',
 'O14867',
 'O14874',
 'O14879',
 'O14896',
 'O14907',
 'O14924',
 'O14926',
 'O14929',
 'O14933',
 'O14939',
 'O14949',
 'O14958',
 'O14966',
 'O14967',
 'O14974',
 'O14975',
 'O14976',
 'O14980',
 'O14983',
 'O15014',
 'O15015',
 'O15018',
 'O15020',
 'O15031',
 'O15037',
 'O15040',
 'O15047',
 'O15061',
 'O15063',
 'O15066',
 'O15067',
 'O15069',
 'O15075',
 'O15084',
 'O15085',
 'O15091',
 'O15111',
 'O15116',
 'O15117',
 'O15118',
 'O15119',
 'O15120',
 'O15121',
 'O15127',
 'O15143',
 'O15144',
 'O15145',
 'O15156',
 'O15164',
 'O15169',
 'O15173',
 'O15195',
 'O15204',
 'O15211',
 'O15212',
 'O15213',
 'O15217',
 'O15226',
 'O15228',
 'O15229',
 'O15230',
 'O15231',
 'O15235',
 'O15239',
 'O15240',
 'O15245',
 'O15247',
 'O15254',
 'O15258',
 'O15264',
 'O15269',
 'O15270',
 'O15273',
 'O15294',
 'O15344',
 'O15354',
 'O15355',
 'O15357',
 'O15371',
 'O15379',
 'O15381',
 'O15397',
 'O15400',
 'O15427',
 'O15431',
 'O15438',
 'O15439',
 'O15446',
 'O15455',
 'O15460',
 'O15479',
 'O15498',
 'O15511',
 'O15523',
 'O15540',
 'O15541',
 'O15551',
 'O43143',
 'O43147',
 'O43148',
 'O43149',
 'O43150',
 'O43155',
 'O43156',
 'O43157',
 'O43164',
 'O43166',
 'O43172',
 'O43181',
 'O43182',
 'O43184',
 'O43237',
 'O43242',
 'O43252',
 'O43264',
 'O43280',
 'O43281',
 'O43290',
 'O43293',
 'O43294',
 'O43295',
 'O43303',
 'O43306',
 'O43310',
 'O43318',
 'O43324',
 'O43353',
 'O43379',
 'O43390',
 'O43395',
 'O43402',
 'O43422',
 'O43490',
 'O43505',
 'O43516',
 'O43520',
 'O43524',
 'O43566',
 'O43581',
 'O43583',
 'O43592',
 'O43615',
 'O43639',
 'O43660',
 'O43665',
 'O43676',
 'O43677',
 'O43678',
 'O43681',
 'O43692',
 'O43704',
 'O43707',
 'O43715',
 'O43719',
 'O43739',
 'O43741',
 'O43747',
 'O43752',
 'O43765',
 'O43772',
 'O43776',
 'O43805',
 'O43809',
 'O43813',
 'O43815',
 'O43818',
 'O43819',
 'O43822',
 'O43823',
 'O43824',
 'O43829',
 'O43852',
 'O43854',
 'O43861',
 'O43865',
 'O43866',
 'O43895',
 'O43896',
 'O43903',
 'O43913',
 'O43920',
 'O43927',
 'O43929',
 'O60216',
 'O60218',
 'O60220',
 'O60237',
 'O60240',
 'O60243',
 'O60244',
 'O60245',
 'O60262',
 'O60264',
 'O60268',
 'O60279',
 'O60287',
 'O60292',
 'O60293',
 'O60296',
 'O60303',
 'O60306',
 'O60307',
 'O60308',
 'O60318',
 'O60331',
 'O60336',
 'O60343',
 'O60346',
 'O60361',
 'O60443',
 'O60447',
 'O60449',
 'O60462',
 'O60476',
 'O60486',
 'O60487',
 'O60488',
 'O60493',
 'O60494',
 'O60500',
 'O60502',
 'O60503',
 'O60506',
 'O60507',
 'O60516',
 'O60518',
 'O60522',
 'O60547',
 'O60563',
 'O60565',
 'O60566',
 'O60568',
 'O60583',
 'O60603',
 'O60609',
 'O60635',
 'O60645',
 'O60656',
 'O60658',
 'O60662',
 'O60664',
 'O60674',
 'O60678',
 'O60684',
 'O60687',
 'O60701',
 'O60725',
 'O60739',
 'O60749',
 'O60760',
 'O60763',
 'O60783',
 'O60784',
 'O60825',
 'O60826',
 'O60829',
 'O60832',
 'O60844',
 'O60861',
 'O60869',
 'O60870',
 'O60884',
 'O60885',
 'O60890',
 'O60906',
 'O60911',
 'O60921',
 'O60927',
 'O60930',
 'O60942',
 'O75051',
 'O75054',
 'O75061',
 'O75063',
 'O75064',
 'O75083',
 'O75094',
 'O75096',
 'O75110',
 'O75112',
 'O75113',
 'O75131',
 'O75132',
 'O75146',
 'O75150',
 'O75151',
 'O75155',
 'O75157',
 'O75164',
 'O75165',
 'O75170',
 'O75173',
 'O75182',
 'O75185',
 'O75191',
 'O75306',
 'O75323',
 'O75330',
 'O75339',
 'O75340',
 'O75348',
 'O75351',
 'O75355',
 'O75356',
 'O75362',
 'O75363',
 'O75366',
 'O75367',
 'O75368',
 'O75369',
 'O75379',
 'O75380',
 'O75381',
 'O75385',
 'O75394',
 'O75396',
 'O75400',
 'O75420',
 'O75427',
 'O75436',
 'O75438',
 'O75439',
 'O75446',
 'O75449',
 'O75452',
 'O75460',
 'O75475',
 'O75477',
 'O75487',
 'O75489',
 'O75506',
 'O75525',
 'O75526',
 'O75528',
 'O75531',
 'O75533',
 'O75534',
 'O75554',
 'O75558',
 'O75563',
 'O75569',
 'O75570',
 'O75582',
 'O75594',
 'O75600',
 'O75604',
 'O75607',
 'O75628',
 'O75635',
 'O75636',
 'O75643',
 'O75663',
 'O75683',
 'O75688',
 'O75691',
 'O75694',
 'O75695',
 'O75715',
 'O75717',
 'O75746',
 'O75751',
 'O75781',
 'O75791',
 'O75792',
 'O75795',
 'O75800',
 'O75808',
 'O75815',
 'O75822',
 'O75828',
 'O75843',
 'O75844',
 'O75864',
 'O75874',
 'O75881',
 'O75882',
 'O75884',
 'O75886',
 'O75891',
 'O75897',
 'O75907',
 'O75909',
 'O75911',
 'O75915',
 'O75923',
 'O75934',
 'O75936',
 'O75937',
 'O75940',
 'O75947',
 'O75953',
 'O75962',
 'O75964',
 'O75969',
 'O75976',
 'O75995',
 'O76003',
 'O76013',
 'O76015',
 'O76027',
 'O76031',
 'O76038',
 'O76041',
 'O76070',
 'O76071',
 'O76076',
 'O76094',
 'O76095',
 'O76096',
 'O94760',
 'O94763',
 'O94769',
 'O94776',
 'O94804',
 'O94805',
 'O94806',
 'O94808',
 'O94811',
 'O94817',
 'O94819',
 'O94822',
 'O94826',
 'O94829',
 'O94830',
 'O94855',
 'O94864',
 'O94874',
 'O94885',
 'O94886',
 'O94887',
 'O94888',
 'O94903',
 'O94906',
 'O94910',
 'O94911',
 'O94913',
 'O94916',
 'O94919',
 'O94925',
 'O94927',
 'O94992',
 'O95049',
 'O95081',
 'O95084',
 'O95104',
 'O95139',
 'O95140',
 'O95149',
 'O95154',
 'O95155',
 'O95159',
 'O95163',
 'O95164',
 'O95168',
 'O95169',
 'O95171',
 'O95182',
 'O95183',
 'O95197',
 'O95202',
 'O95210',
 'O95218',
 'O95219',
 'O95236',
 'O95243',
 'O95248',
 'O95251',
 'O95274',
 'O95278',
 'O95292',
 'O95294',
 'O95295',
 'O95297',
 'O95298',
 'O95302',
 'O95336',
 'O95340',
 'O95342',
 'O95347',
 'O95352',
 'O95365',
 'O95373',
 'O95376',
 'O95382',
 'O95388',
 'O95391',
 'O95396',
 'O95400',
 'O95405',
 'O95425',
 'O95428',
 'O95429',
 'O95445',
 'O95456',
 'O95466',
 'O95470',
 'O95477',
 'O95478',
 'O95479',
 'O95486',
 'O95487',
 'O95497',
 'O95544',
 'O95551',
 'O95571',
 'O95573',
 'O95602',
 'O95613',
 'O95625',
 'O95626',
 'O95628',
 'O95630',
 'O95631',
 'O95671',
 'O95674',
 'O95678',
 'O95684',
 'O95685',
 'O95696',
 'O95714',
 'O95716',
 'O95721',
 'O95741',
 'O95747',
 'O95749',
 'O95758',
 'O95760',
 'O95782',
 'O95786',
 'O95801',
 'O95810',
 'O95816',
 'O95817',
 'O95822',
 'O95831',
 'O95833',
 'O95834',
 'O95837',
 'O95848',
 'O95861',
 'O95864',
 'O95865',
 'O95873',
 'O95881',
 'O95886',
 'O95905',
 'O95926',
 'O95954',
 'O95980',
 'O95989',
 'O95994',
 'O96005',
 'O96006',
 'O96007',
 'O96008',
 'O96009',
 'O96011',
 'O96013',
 'O96018',
 'O96019',
 'P00156',
 'P00167',
 'P00326',
 'P00338',
 'P00352',
 'P00367',
 'P00374',
 'P00387',
 'P00390',
 'P00395',
 'P00403',
 'P00414',
 'P00441',
 'P00450',
 'P00480',
 'P00488',
 'P00491',
 'P00492',
 'P00505',
 'P00519',
 'P00558',
 'P00734',
 'P00740',
 'P00742',
 'P00747',
 'P00748',
 'P00846',
 'P00918',
 'P00966',
 'P01008',
 'P01009',
 'P01019',
 'P01023',
 'P01024',
 'P01031',
 'P01034',
 'P01036',
 'P01037',
 'P01040',
 'P01042',
 'P01111',
 'P01112',
 'P01116',
 'P01185',
 'P01189',
 'P01210',
 'P01225',
 'P01229',
 'P01266',
 'P01275',
 'P01303',
 'P01344',
 'P01599',
 'P01601',
 'P01602',
 'P01619',
 'P01700',
 'P01701',
 'P01703',
 'P01705',
 'P01706',
 'P01709',
 'P01714',
 'P01717',
 'P01721',
 'P01730',
 'P01742',
 'P01743',
 'P01762',
 'P01763',
 'P01764',
 'P01766',
 'P01767',
 'P01780',
 'P01817',
 'P01824',
 'P01833',
 'P01871',
 'P01911',
 'P02008',
 'P02042',
 'P02100',
 'P02452',
 'P02458',
 'P02461',
 'P02462',
 'P02533',
 'P02538',
 'P02549',
 'P02585',
 'P02647',
 'P02649',
 'P02671',
 'P02675',
 'P02689',
 'P02730',
 'P02741',
 'P02743',
 'P02745',
 'P02747',
 'P02748',
 'P02749',
 'P02750',
 'P02751',
 'P02760',
 'P02763',
 'P02765',
 'P02775',
 'P02776',
 'P02787',
 'P02790',
 'P02792',
 'P03886',
 'P03891',
 'P03905',
 'P03915',
 'P03928',
 'P03950',
 'P03951',
 'P03973',
 'P04003',
 'P04004',
 'P04035',
 'P04040',
 'P04049',
 'P04066',
 'P04080',
 'P04083',
 'P04114',
 'P04179',
 'P04180',
 'P04181',
 'P04196',
 'P04217',
 'P04259',
 'P04264',
 'P04271',
 'P04275',
 'P04350',
 'P04406',
 'P04430',
 'P04746',
 'P04792',
 'P04818',
 'P04839',
 'P04843',
 'P04844',
 'P04899',
 'P04920',
 'P05023',
 'P05026',
 'P05060',
 'P05062',
 'P05091',
 'P05106',
 'P05108',
 'P05109',
 'P05120',
 'P05121',
 'P05129',
 'P05141',
 'P05154',
 'P05160',
 'P05162',
 'P05164',
 'P05177',
 'P05181',
 'P05186',
 'P05187',
 'P05198',
 'P05204',
 'P05230',
 'P05362',
 'P05386',
 'P05387',
 'P05412',
 'P05423',
 'P05451',
 'P05455',
 'P05543',
 'P05546',
 'P05556',
 'P05771',
 'P05783',
 'P05787',
 'P05937',
 'P05976',
 'P05997',
 'P06127',
 'P06133',
 'P06213',
 'P06241',
 'P06310',
 'P06312',
 'P06331',
 'P06340',
 'P06396',
 'P06401',
 'P06576',
 'P06702',
 'P06703',
 'P06727',
 'P06732',
 'P06737',
 'P06748',
 'P06753',
 'P06756',
 'P06858',
 'P06870',
 'P07093',
 'P07098',
 'P07099',
 'P07101',
 'P07148',
 ...]

In [16]:
# Debug: Check the raw SHAP values shape that mlmarker sees
import shap

explainer = shap.TreeExplainer(model.model)
shap_values = explainer.shap_values(processed_sample)

print("Type of shap_values:", type(shap_values))
if isinstance(shap_values, list):
    print("SHAP is a list with", len(shap_values), "elements")
    print("Each element shape:", shap_values[0].shape)
    print("np.array(shap_values).shape:", np.array(shap_values).shape)
else:
    print("SHAP array shape:", shap_values.shape)

# This is what mlmarker does:
original_order = np.array(shap_values).shape
print("\noriginal_order (shape tuple):", original_order)
print("Looking for 1 in tuple:", 1 in original_order)
print("Looking for", len(model.model.classes_), "(num classes) in tuple:", len(model.model.classes_) in original_order)
print("Looking for", len(model.explainability.features), "(num features) in tuple:", len(model.explainability.features) in original_order)

Type of shap_values: <class 'list'>
SHAP is a list with 34 elements
Each element shape: (1, 11891)
np.array(shap_values).shape: (34, 1, 11891)

original_order (shape tuple): (34, 1, 11891)
Looking for 1 in tuple: True
Looking for 34 (num classes) in tuple: True
Looking for 5979 (num features) in tuple: False

In [15]:
len(sorted(['Nasal Polyps', 'Duodenum', 'Small intestine', 'Parotid gland', 'Colon', 'Liver', 'Ovary', 'Testis', 'B-cells', 'Prostate', 'Esophagus', 'Skeletal muscle', 'Stomach', 'Adrenal gland', 'Appendix', 'Salivary gland', 'Urinary bladder', 'Smooth muscle', 'Oviduct', 'Lung', 'Pituitary gland', 'Brain', 'Placenta', 'Tonsil', 'Endometrium', 'Rectum', 'Lymph node', 'Thyroid', 'Bone marrow', 'Kidney', 'Adipose tissue', 'Heart', 'Monocytes', 'Spleen']))

34

In [ ]:
# Check what load_sample does to the sample
print("Input sample shape:", processed_sample.shape)
print("Model features count:", len(model.explainability.features))
print("Sample stored in model shape:", model.explainability.sample.shape)
print("\nAre they the same?", model.explainability.sample.shape[1] == len(model.explainability.features))